<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-05T19:03:28 IST" name="Default suite" finished-at="2025-02-05T19:05:10 IST" duration-ms="101834">
    <groups>
    </groups>
    <test started-at="2025-02-05T19:03:28 IST" name="Default test" finished-at="2025-02-05T19:05:10 IST" duration-ms="101834">
      <class name="testCases.TaskTwo">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.TaskTwo@36ebc363]" started-at="2025-02-05T19:03:29 IST" name="setUp" finished-at="2025-02-05T19:05:10 IST" duration-ms="101226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="searchingProducts()[pri:0, instance:testCases.TaskTwo@36ebc363]" started-at="2025-02-05T19:05:10 IST" name="searchingProducts" finished-at="2025-02-05T19:05:10 IST" duration-ms="19" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test can only run between 3 PM and 6 PM]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test can only run between 3 PM and 6 PM
at testCases.TaskTwo.searchingProducts(TaskTwo.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchingProducts -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TaskTwo@36ebc363]" started-at="2025-02-05T19:05:10 IST" name="tearDown" finished-at="2025-02-05T19:05:10 IST" duration-ms="500" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TaskTwo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
